config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get    '/places', to: 'places#index'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :places
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_avatar.html.erb
<div class= "avatar-circle" >
  <span class= "initials">
    
  </span>
</div>
  

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="card-space z-depth-3">
    <div class="field">
      <%= f.text_area :content, placeholder: "¿Cual es tu idea?", class: 'materialize-textarea' %>
    </div>
    
    <%= f.submit "Post", class: "waves-effect waves-light btn green accent-3 z-depth-4" %>
    
    <div class="file-field input-field ">
      <div class="btn purple accent-2 z-depth-4">
        <input type="file" multiple>
        <i class="material-icons">camera_alt</i>
        <input type="file" accept="image/*;capture=camera">
      </div>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>
      <div class="file-path-wrapper">
        <input class="file-path" type="text">
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Tu archivo es demasiado pesado, el minimo es de 5mb .');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    Siguiendo
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Seguidores
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "Ver mi perfil", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>