config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get    '/places', to: 'places#index'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :places
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  default_scope -> { order(created_at: :desc) }
  geocoded_by :address, :latitude  => :lat, :longitude => :lon
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  mount_uploader :picture, PictureUploader
  
  def address
        
  end
    
  private
    
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Debe ser menos de 5mb")
      end
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def index
    posts = []
    if filtered_places = current_user.following.each{|x|  x.microposts.each{|m| posts << m}}
      @places = Place.order('created_at DESC')
    end
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.build(place_params)
    if @place.save
      flash[:success] = "Tu lugar ha sido creado!"
      redirect_to places_path
    else
      render 'new'
    end
  end
  
  def destroy
    @place.destroy
    flash[:success] = "Tu lugar ha sido borrado!"
    redirect_to places_path
  end

  private

  def place_params
    params.require(:place).permit(:title, :address, :visited_by, :picture)
  end
  
  def correct_user
   @place = current_user.places.find_by(id: params[:id])
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<div class= "container center">
  <div class="col s12">
    <div class=" col s12">
      <%= form_for @place do |f| %>
      
      <div class="col s12 m6 input-field  container">
        <i class="material-icons prefix">place</i>
        <%= f.text_area :title, class: 'materialize-textarea' %>
        <label for="icon_prefix"><%= f.label :lugar %></label>
      </div>
      
      <div class="col s12 m6 input-field  container">
        <i class="material-icons prefix">explore</i>
        <%= f.text_area :title, class: 'materialize-textarea' %>
        <label for="icon_prefix"><%= f.label :address, 'Dirección' %></label>
      </div>
          
        <div class="file-field input-field ">
          <div class="btn purple accent-2 z-depth-4">
            <i class="material-icons">camera_alt</i>
            <input type="file" multiple>
            <input type="file" accept="image/*;capture=camera">
          </div>
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div></br>
        <%= f.submit 'Agregar', class: 'btn btn-primary green accent-3 z-depth-4' %>
      <% end %>
    </div>
  </div>
</div>

app/views/places/_place.html.erb
<li>
  <%= link_to place.title, place_path(place) %>
  visitado por <strong><%= place.visited_by %></strong>
  <span class="user"><%= link_to place.user.name, place.user %></span>
</li>

app/views/places/index.html.erb
<header><h1 class="display-4">Lugares</h1></header>

<div>
  <%= link_to new_place_path, class: 'btn btn-primary btn-lg green accent-3 z-depth-5' do %>
    <i class="material-icons"></i>Agrega un lugar
  <% end %>
</div></br>


<div class="section">
  <div class="places-grid">
    <div class="row">
      <% @places.each do |place| %>
      <div class="col s4 l4 m4 places-holder">
        <div class="card hoverable">
          <div class="card-image materialboxed" width="50">
            <%= image_tag place.picture.url if place.picture %>
            <span class="picture responsive-img"></span>
          </div>
          <div class="card-content mar-bottom">
            <%= render place %>
            <% if current_user?(place.user)%>
              <%= link_to place, method: :delete, class:"btn-floating halfway-fab waves-effect waves-light red", data: { confirm: "Seguro que quieres eliminar?" } do %>
                <i class="material-icons">delete</i>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/places/new.html.erb
<header><h1 class="display-4">Agrega un lugar</h1></header>
<%= render 'form' %>

app/views/places/show.html.erb
<header><h1 class="display-4"><%= @place.title %></h1></header>

<p>Address: <%= @place.address %></p>
<p>Coordinates: <%= @place.latitude %> <%= @place.longitude %></p>