config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  
  get    '/places', to: 'places#index'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :places
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<header class="top">
  <div class="col s12">
    <%= link_to " T ", root_path, id: "logo" %>
    <nav class="rosa-mex nav-wrapper z-depth-5">
      <div class="bar">
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons margin-left">menu</i></a>
        <ul class=" hide-on-med-and-down">
          <% if logged_in? %>
            <li><%= link_to "Inicio", root_path %><i class="material-icons head">home</i></li>
            <li><%= link_to "Lugares", places_path %><i class="material-icons head">map</i></li>
    
            <li class="search">
              <div class="search-wrapper white-text text-accent-3 bar-size2 hoverable">
                <%= form_tag(users_path, :method => "get", id: "search-form") do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Buscar" %>
                  <select class="selectpicker" data-live-search="true">
                    
                  </select>
                <% end %>
              </div>
            </li>
            <li>
              <a href="#" class='dropdown-button ' href='#' data-activates='dropdown1'>Cuenta</a>
              <ul id='dropdown1' class='dropdown-content' col s12 m6 l3>
                <li><%= link_to "Perfil", current_user %></li>
                <li><%= link_to "Ajustes", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Cerrar Sesión", logout_path, method: "delete" %>
                </li>
              </ul>
              <i class="material-icons head">tune</i>
            </li>
           
          <% else %>
            <li><%= link_to "Iniciar Sesión", login_path %><i class="material-icons head">filter_vintage</i></li>
            <li><%= link_to "Lugares", places_path %><i class="material-icons head">map</i></li>
          <% end %>
        </ul>
        
        <ul class="side-nav mex-blu" id="mobile-demo">
          <% if logged_in? %>
          <li><div class="user-view size">
            <div class="background-size">
              <%= cover_for (current_user) %>
            </div>
            <div class="top-image"> <%= gravatar_for (current_user) %> </div>
            <span class="white-text name"><%= current_user.name %></span>
            <span class="white-text email"><%= current_user.email %></span></a>
          </div></li>
          <% end %>
          
          <li class="search">
            <div class="search-wrapper card green-text text-accent-3 bar-size z-depth-1 hoverable">
              <%= form_tag(users_path, :method => "get", id: "search-form") do %>
                  <%= text_field_tag :search, params[:search], placeholder: "Buscar" %>
                  <select class="selectpicker" data-live-search="true">
                    
                  </select>
                <% end %>
            </div>
          </li>
          
          <li><%= link_to "Inicio", root_path %></li>
          <li><%= link_to "Lugares", places_path %></li>
          <% if logged_in? %>
            <li><%= link_to "Usuarios", users_path %></li>
          <li>
            <ul>
              <li><%= link_to "Perfil", current_user %></li>
              <li><%= link_to "Ajustes", edit_user_path(current_user) %></li>
            </ul>
            <li><div class="divider"></div></li>
              <%= link_to "Cerrar Sesión", logout_path, method: "delete", class:"waves-effect black-text" %>
            </li>
          <% else %>
            <li><%= link_to "Iniciar Sesión", login_path %></li>
          <% end %>
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons" style="
    margin-left: -20px;
" >menu</i></a>
        </ul>
      </div>
    </nav>
  </div>
</header>
<script>
  $(".button-collapse").sideNav();
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="theme-color" content="#ec407a">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab" rel="stylesheet">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="container col s12">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>